Feature/task 5
ozoncp/ocp-howto-api pull request #2
Opened 2021-06-06 09:38 UTC by 6axp

- Добавил интерфейс Alarmer и имплементацию periodAlarmer, которая выдает сигналы через заданные промежутки времени
- Добавил интерфейс Saver и его имплементацию, которая по сигналу от Alarmer'а или по Close() сливает данные через Flusher
- Добавил генерацию моков Flusher для тестов (файлы с моками наверное можно в .gitignore добавить?)
- Написал тесты для periodAlarmer и saver

2021-06-06 18:36 UTC, xmikasax requested changes

2021-06-06 18:36 UTC, xmikasax commented on internal/alarmer/alarmer.go
> +			alarmer.alarm <- struct{}{}
А если никто не слушает alarm в данный момент? Я бы добавил еще select с default'ом

2021-06-06 18:36 UTC, xmikasax commented on internal/saver/saver.go
> +		saver.queue = createEmptySlice(saver.capacity)
Думаю, что в твоем случае нет смысла выделять новый слайс, можно реслайснуть старый queue = queue[:0]

Но советую почитать https://stackoverflow.com/questions/28432658/does-go-garbage-collect-parts-of-slices

2021-06-06 18:36 UTC, xmikasax commented on internal/saver/saver.go
> +	close(saver.done)
Аналогично

2021-06-06 18:36 UTC, xmikasax commented on internal/saver/saver.go
> +	saver.done <- struct{}{}
Не ждешь завершения poll, можешь потерять данные

2021-06-06 19:31 UTC, 6axp commented on internal/saver/saver.go
> +	saver.done <- struct{}{}
Если честно, не очень понял. По Close() я всего лишь выдаю сигнал done. poll() этот сигнал ловит, сливает все данные и завершается. Как нужно ждать poll() и как могут потеряться данные?

2021-06-07 09:16 UTC, xmikasax commented on internal/saver/saver.go
> +	saver.done <- struct{}{}
Если ты в main делаешь defer saver.Close(), то функция main завершится сразу после записи в канал done. А это может произойти до завершения функции Flush. Так данные и потеряются

2021-06-07 09:26 UTC, 6axp commented on internal/saver/saver.go
> +	saver.done <- struct{}{}
Так у меня же по Close() просто записывается сигнал done и ничего более. А Flush() происходит в poll(). Flush() завершится и только после этого словится сигнал done

2021-06-07 09:39 UTC, xmikasax commented on internal/saver/saver.go
> +	saver.done <- struct{}{}
У тебя 2 горутины, main и poll.

main вызывает close, пишет в done
poll читает из done и вызывает flush
flush долго работает в poll
main выходит из close после записи в done, flush все еще идет в горутине poll
main завершается, завершается программа
flush не успел сохранить данные

2021-06-07 10:09 UTC, 6axp commented on internal/saver/saver.go
> +	saver.done <- struct{}{}
То есть, все горутины сразу завершаются при завершении main? Ну да, теперь всё понятно. Получается, надо просто добавить сигнал, который выдается по завершению poll() и ждать его в Close() ?
Я еще видел, кто-то по Close() просто закрывает канал done. Так тоже можно?

2021-06-07 10:25 UTC, xmikasax commented on internal/saver/saver.go
> +	saver.done <- struct{}{}
Они закрывают канал done и делают flush прямо в Close. Тогда данные не теряются. Если завершается main, то завершается полностью программа, никого не ждет. Чтобы подождать можно либо отдельный канал, как ты сказал, либо воспользоваться WaitGroup

2021-06-07 13:35 UTC, 6axp commented on internal/saver/saver.go
> +	saver.done <- struct{}{}
Спасибо, поправил. Close() теперь шлёт сигнал close и ждёт done. Добавил соответствующий тест. Всё остальное тоже поправил

2021-06-08 08:41 UTC, xmikasax approved these changes

2021-06-08 08:54 UTC, merged