Feature/task 8
ozoncp/ocp-howto-api pull request #5
Opened 2021-06-16 11:05 UTC by 6axp

- Добавил в API ручки MultiCreateHowto() и UpdateHowto()
- Добавил в Repo метод UpdateHowto()
- Изменил Repo.AddHowtos(). Теперь, для множественного инсерта в базу данных, коллекция сначала режется на пачки. Размер пачки задается в Repo.New()
- Добавил спаны в MultiCreateHowto() и ниже по стеку вызовов. В другие функции не добавлял, так как по заданию нужно было добавить только сюда.
- Добавил CUD метрики. В ручках увеличиваются счетчики в случае успешного выполнения соответствующей операции. Наверное, имеет еще смысл добавлять метрики о запрошенных операциях, тогда их можно было бы сравнивать. Но по заданию нужно было добавить только успешные.
- Добавил Producer, который пишет в кафку события. В задании не было сказано, где и как его использовать, а просто добавить. Так что он нигде не используется. Я поставил кафку в докере и проверил - вроде работает
- Добавил композ файл

2021-06-16 16:55 UTC, siriusfreak requested changes

2021-06-16 16:55 UTC, siriusfreak commented on api/ocp-howto-api/ocp-howto-api.proto
> +    rpc UpdateHowtoV1(UpdateHowtoV1Request) returns (UpdateHowtoV1Response){
лучше использовать empty 

https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.Empty

2021-06-16 16:55 UTC, siriusfreak commented on cmd/ocp-howto-api/main.go
> +	dbDsn          = "user=postgres password=postgres dbname=postgres sslmode=disable"
Хранение паролей в коде, плохая практика, вынеси в отдельный файл. Как и весь конфиг

2021-06-16 16:55 UTC, siriusfreak commented on cmd/ocp-howto-api/main.go
> +	dbDsn          = "user=postgres password=postgres dbname=postgres sslmode=disable"
При этом надо добавить шаблон этого конфига в репу, чтобы копируя себе локально разработчик знал что должно быть в конфиге

2021-06-16 16:55 UTC, siriusfreak commented on docker-compose.yml
> +  kafka:
как необходимый доп -- сделай два-три брокера кафки.

2021-06-16 17:09 UTC, 6axp commented on cmd/ocp-howto-api/main.go
> +	dbDsn          = "user=postgres password=postgres dbname=postgres sslmode=disable"
то есть надо добавить конфиг с незаполненными данными, а потом добавить его в .gitignore?

2021-06-16 17:13 UTC, 6axp commented on api/ocp-howto-api/ocp-howto-api.proto
> +    rpc UpdateHowtoV1(UpdateHowtoV1Request) returns (UpdateHowtoV1Response){
А я намеренно не стал использовать empty. Так вроде как симметричнее получается: request-response. И единообразно. Заодно, если я вдруг захочу добавить что-то в ответ, то не придется сильно менять - просто поле добавить.
А почему empty лучше?

2021-06-17 09:41 UTC, siriusfreak approved these changes

2021-06-17 09:42 UTC, merged

2021-06-17 13:09 UTC, rusdevops commented on cmd/ocp-howto-api/main.go
> +	dbDsn          = "user=postgres password=postgres dbname=postgres sslmode=disable"
как вариант ))